import { rm } from 'node:fs/promises';
import { defineConfig } from 'cypress';
import createBundler from '@bahmutov/cypress-esbuild-preprocessor';
import { addCucumberPreprocessorPlugin } from '@badeball/cypress-cucumber-preprocessor';
import { createEsbuildPlugin } from '@badeball/cypress-cucumber-preprocessor/esbuild';
import { ReportingSubject } from './src/core/reporting/ReportingSubject';
import { ConsoleObserver } from './src/core/reporting/ConsoleObserver';
import { GithubActionsSummaryObserver } from './src/core/reporting/GithubActionsSummaryObserver';
import type { TestResult } from './src/core/reporting/Observer';

export default defineConfig({
  projectId: '5v45hh',
  viewportWidth: 1280,
  viewportHeight: 800,
  e2e: {
    baseUrl: 'https://omnipizza-frontend.onrender.com',
    specPattern: ['cypress/e2e/**/*.feature'],
    supportFile: 'cypress/support/e2e.ts',
    async setupNodeEvents(on, config) {
      await addCucumberPreprocessorPlugin(on, config);
      // The .md text loader is what lets cy.prompt's natural-language steps
      // live in a markdown file instead of TypeScript string literals: the
      // import becomes a plain string at bundle time, so the strategy that
      // consumes it stays synchronous (cy.fixture/cy.readFile would force a
      // Chainable through the whole CheckoutUiStrategy interface).
      on(
        'file:preprocessor',
        createBundler({ plugins: [createEsbuildPlugin(config)], loader: { '.md': 'text' } }),
      );

      // Replaces trashAssetsBeforeRuns, which cannot succeed on Windows.
      // Cypress's bundled `trash` shells out to windows-trash.exe, and that
      // binary exits 255 on any directory containing a file inside a
      // subdirectory - bisected 2026-08-21: a flat directory of files
      // trashes fine, an empty subdirectory trashes fine, one file one level
      // down fails. Cypress's own screenshot layout is always
      // screenshots/<spec path>/<test name>.png, so the feature is
      // permanently broken here and prints a warning on every single run.
      //
      // Note this is a permanent delete rather than a Recycle Bin move.
      // That is fine for these two folders specifically - both are
      // gitignored and regenerated by the next run - but it is a real
      // behaviour change from what it replaces.
      on('before:run', async () => {
        const folders = [config.screenshotsFolder, config.videosFolder];
        await Promise.all(
          folders.filter((folder): folder is string => typeof folder === 'string').map((folder) => rm(folder, { recursive: true, force: true })),
        );
      });

      const reportingSubject = new ReportingSubject();
      reportingSubject.subscribe(new ConsoleObserver());
      reportingSubject.subscribe(new GithubActionsSummaryObserver(process.env.GITHUB_STEP_SUMMARY));

      on('after:spec', (spec, results) => {
        const sliceMatch = spec.relative.match(/[\\/]e2e[\\/]([^\\/]+)[\\/]/);
        const slice = sliceMatch ? sliceMatch[1] : 'unknown';
        const testResults = (results?.tests ?? []).map((t) => ({
          specPath: spec.relative,
          title: t.title.join(' > '),
          state: t.state as TestResult['state'],
          durationMs: t.duration ?? 0,
          slice,
        }));
        reportingSubject.notify(testResults);
      });

      return config;
    },
  },
  // `expose`, not `env`: Cypress 15 deprecated Cypress.env() because any
  // browser code on the page could read it. Nothing this framework passes
  // is a secret - the backend URL and the UI-strategy switch are both
  // public config - so both moved to expose, and no Cypress.env() call is
  // left in our own code. If a real secret ever has to reach a test,
  // cy.env() is the API for that.
  //
  // allowCypressEnv STAYS ON, and that is not an oversight. Setting it to
  // false is what the deprecation warning asks for, but it makes every
  // single spec fail: @badeball/cypress-cucumber-preprocessor calls
  // `createTestFilter(gherkinDocument, Cypress.env())` while building the
  // tests for each .feature - its tag-filtering path, unconditional, on
  // every file. Verified live 2026-08-21: with it off, 3 of 3 specs die
  // before a test runs. 26.0.0 is the latest published version, so there is
  // no release to upgrade into yet.
  //
  // So the run-level warning stays until the preprocessor migrates. Retry
  // this flag on the next @badeball release; the only other route is
  // patching the dependency, which trades a cosmetic warning for a
  // permanent maintenance burden.
  expose: {
    apiUrl: 'https://omnipizza-backend.onrender.com',
  },
  trashAssetsBeforeRuns: false,
  reporter: 'mochawesome',
  reporterOptions: {
    reportDir: 'cypress/reports/mochawesome',
    overwrite: false,
    html: true,
    json: true,
  },
});
